set(she_base64 "she_base64")
set(${she_base64}_FOUND "1")
set(${she_base64}_INCLUDE_DIR   "${CMAKE_PREFIX_PATH}/include")
set(${she_base64}_LIBRARIES     "${CMAKE_PREFIX_PATH}/lib")
set(${she_base64}_LINK_DIRECTORIES  "she_base64")
